//-----------------------------------------------------------------------------
//
// ImageLib Sources
// Copyright (C) 2000-2009 by Denton Woods
// Last modified: 01/24/2009
//
// Filename: src-IL/include/il_internal.h
//
// Description: Internal stuff for DevIL
//
//-----------------------------------------------------------------------------
#ifndef INTERNAL_H
#define INTERNAL_H

/* for Doxygen to know to document this file */
/** @file */

// Local headers
/*#if (defined(_WIN32) || defined(_WIN64)) && !defined(HAVE_CONFIG_H)
	#define HAVE_CONFIG_H
#endif*/
#ifdef HAVE_CONFIG_H //if we use autotools, we have HAVE_CONFIG_H defined and we have to look for it like that
	#include "config.h"
#else // If we do not use autotools, we have to point to (possibly different) config.h than in the opposite case
#	include <IL/config.h>
/* Usage of autotools also ensures that the IL_BUILD_LIBRARY define is passed via commandline during compilation (smarter) */
#	define IL_BUILD_LIBRARY
#endif

// Standard headers
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <errno.h>

/* Can we supply native language support? */
#ifdef ENABLE_NLS
#define BIND_TEXTDOMAIN_IFNEEDED bindtextdomain(PACKAGE, LOCALEDIR)
#else
#define BIND_TEXTDOMAIN_IFNEEDED 
#endif /* ENABLE_NLS */

#ifdef BUILD_MODULES
/**
 * We want modular DevIL.
 */
#include <ltdl.h>
#define SET_FORMAT(format, modules, id, extensions) Set_format_modular(format, modules, # id, extensions)
#define INIT_LTDL_IFNEEDED lt_dlinit()
#define CREATE_MODULES_IFNEEDED(x) Modules * x = create_modules()

#else  /* !BUILD_MODULES */
/**
 * We want modules to be statically linked.
 * Therefore we want to avoid all module - related stuff and also create the SET_FORMAT macro
 */
#define INIT_LTDL_IFNEEDED
#define CREATE_MODULES_IFNEEDED(x) 
#define SET_FORMAT(format, modules, id, extensions) Set_format_static(format, # id, extensions\
		, ilIsValid_ ## id ## _PTR, ilIsValidF_ ## id ## _PTR, ilIsValidL_ ## id ## _PTR\
		, ilLoad_ ## id ## _PTR, ilLoadF_ ## id ## _PTR, ilLoadL_ ## id ## _PTR\
		, ilSave_ ## id ## _PTR, ilSaveF_ ## id ## _PTR, ilSaveL_ ## id ## _PTR)
#endif /* !BUILD_MODULES */

/* We can use the autogenerated declarations here */
#include <IL/ptr_defines.h>

/* pretty useful stuff there regardeless on whether we want to build modules or not */
/* TODO: Move some of that interesting stuff right here */
#include "il_module.h"

/* We want to use logging program-wide, so it has to be here */
#include "il_logging.h"

/* TODO: Maybe that can be removed along with the declarations that are now autogenerated in ptr_defines.h */
#ifdef __cplusplus
extern "C" {
#endif

/* This is OK and won't result in inclusion of wrong headers, 
 * it will search for includes in paths specified to the compiler
 */
#include <IL/il.h>
#include <IL/devil_internal_exports.h>

#include "il_files.h"
#include "il_endian.h"

/* The next macro is asked for from within the "gettext.h" file, 
 * so it MUST BE defined BEFORE its inclusion */
#define DEFAULT_TEXT_DOMAIN PACKAGE
/* This is a convenience file in the include directory that contains lots of strange stuff */
#include "IL/gettext.h"
/* Gettext definitions. They are OK (yes, they are actually LIBRARY VERSIONS of the gettext call) 
 * since there are some redefinitions within the 'gettext.h'
 * They are still OK even when we don't want to use gettext. Or it at least should be like that :-) */
#define N_(str) gettext (str)
#define _(str) gettext (str)

#ifndef _WIN32
	// The Microsoft HD Photo Device Porting Kit has not been ported to anything other
	//  than Windows yet, so we disable this if Windows is not the current platform.
	//#define IL_NO_WDP
#endif//_WIN32

// If we do not want support for game image formats, this define removes them all.
#ifdef IL_NO_GAMES
	#define IL_NO_BLP
	#define IL_NO_DOOM
	#define IL_NO_FTX
	#define IL_NO_IWI
	#define IL_NO_LIF
	#define IL_NO_MDL
	#define IL_NO_ROT
	#define IL_NO_TPL
	#define IL_NO_WAL
#endif//IL_NO_GAMES

// Windows-specific
#ifdef _WIN32
	#ifdef _MSC_VER
		#if _MSC_VER > 1000
			#pragma once
			#pragma intrinsic(memcpy)
			#pragma intrinsic(memset)
			#pragma intrinsic(strcmp)
			#pragma intrinsic(strlen)
			#pragma intrinsic(strcpy)
			
			#if _MSC_VER >= 1300
				#pragma warning(disable : 4996)  // MSVC++ 8/9 deprecation warnings
			#endif
		#endif // _MSC_VER > 1000
	#endif
	#define WIN32_LEAN_AND_MEAN  // Exclude rarely-used stuff from Windows headers
	#include <windows.h>
#endif//_WIN32

#ifdef _UNICODE
	#define IL_TEXT(s) L##s
	#ifndef _WIN32  // At least in Linux, fopen works fine, and wcsicmp is not defined.
		#define wcsicmp wcsncasecmp
		#define _wcsicmp wcsncasecmp
		#define _wfopen fopen
	#endif
	#define iStrCpy wcscpy
#else
	#define IL_TEXT(s) (s)
	#define iStrCpy strcpy
#endif

#ifdef IL_INLINE_ASM
	#if (defined (_MSC_VER) && defined(_WIN32))  // MSVC++ only
		#define USE_WIN32_ASM
	#endif

	#ifdef _WIN64
		#undef USE_WIN32_ASM
	//@TODO: Windows 64 compiler cannot use inline ASM, so we need to
	//  generate some MASM code at some point.
	#endif

	#ifdef _WIN32_WCE  // Cannot use our inline ASM in Windows Mobile.
		#undef USE_WIN32_ASM
	#endif
#endif


/* These ones have to be there. They are read during configure time */
typedef ILboolean (* ilIsValid_ptr)(ILconst_string);
typedef ILboolean (* ilIsValidF_ptr)(ILHANDLE);
typedef ILboolean (* ilIsValidL_ptr)(const void *, ILuint);
typedef ILboolean (* ilLoad_ptr)(ILconst_string);
typedef ILboolean (* ilLoadF_ptr)(ILHANDLE);
typedef ILboolean (* ilLoadL_ptr)(const void *, ILuint);
typedef ILboolean (* ilSave_ptr)(ILconst_string);
typedef ILuint (* ilSaveF_ptr)(ILHANDLE);
typedef ILuint (* ilSaveL_ptr)(void *, ILuint);

/** This structure contains the format-specific functions for each format
 */
struct format_functions
{
	/*@{*/ 
	/** Various "Is valid" callbacks */
	ilIsValid_ptr ilIsValid;
	ilIsValidF_ptr ilIsValidF;
	ilIsValidL_ptr ilIsValidL;
	/*@}*/ 

	/*@{*/ 
	/** and "Load stuff" callbacks */
	ilLoad_ptr ilLoad;
	ilLoadF_ptr ilLoadF;
	ilLoadL_ptr ilLoadL;
	/*@}*/ 

	/*@{*/ 
	/** finally "Save stuff" callbacks */
	ilSave_ptr ilSave;
	ilSaveF_ptr ilSaveF;
	ilSaveL_ptr ilSaveL;
	/*@}*/ 
};
typedef struct format_functions Format_functions;

/** Everything that describes a format
 */
struct format
{
	Format_functions Callbacks;	/**< The callbacks stuff */
	char ** Extensions;	/**< The NULL-pointer-terminated lowercase extension strings, like {"jpg", "jpeg", NULL} */
	char * Name;	/**< Format name, like "JPEG" */
};
typedef struct format Format;

#ifdef BUILD_MODULES
/** This structure stores all loaded modules along with their names and formats they are supposed to handle 
 */
struct modules
{
	char ** Module_names;	/**< What is the name of the module? */
	char ** Module_formats;	/**< What formats do they support? */
	int Num_modules;	/**< How many of modules have we loaded? */

	lt_dlhandle * Module_handles;	/**< What are the respective module handles? */
};
typedef struct modules Modules;

/* Creates a pointer to a valid Modules structure */
Modules * create_modules();
/* Destroys the pointer to the Modules structure and even its contents */
void destroy_modules(Modules * modules);

/** Helper function, used by Set_format, fills the Format_functions structure */
void load_callbacks(const Modules * modules, Format_functions * callbacks, const char * name);

#endif /* BUILD_MODULES */
/** Function fills a Format structure */
void Set_format(Format * format, const char * format_name, const char * format_extensions);

extern Format Formats[IL_FORMATS_COUNT];

extern ILAPI ILimage *iCurImage;
/** We may want to log stuff we do */
extern ILstring ilLogFile; 
/** And we may want to control what we want to log*/
extern ILint ilLogLevel; 

#define BIT_0	0x00000001
#define BIT_1	0x00000002
#define BIT_2	0x00000004
#define BIT_3	0x00000008
#define BIT_4	0x00000010
#define BIT_5	0x00000020
#define BIT_6	0x00000040
#define BIT_7	0x00000080
#define BIT_8	0x00000100
#define BIT_9	0x00000200
#define BIT_10	0x00000400
#define BIT_11	0x00000800
#define BIT_12	0x00001000
#define BIT_13	0x00002000
#define BIT_14	0x00004000
#define BIT_15	0x00008000
#define BIT_16	0x00010000
#define BIT_17	0x00020000
#define BIT_18	0x00040000
#define BIT_19	0x00080000
#define BIT_20	0x00100000
#define BIT_21	0x00200000
#define BIT_22	0x00400000
#define BIT_23	0x00800000
#define BIT_24	0x01000000
#define BIT_25	0x02000000
#define BIT_26	0x04000000
#define BIT_27	0x08000000
#define BIT_28	0x10000000
#define BIT_29	0x20000000
#define BIT_30	0x40000000
#define BIT_31	0x80000000
#define NUL '\0'  // Easier to type and ?portable?
#if !_WIN32 || _WIN32_WCE
	int stricmp(const char *src1, const char *src2);
	int strnicmp(const char *src1, const char *src2, size_t max);
#endif//_WIN32
#ifdef _WIN32_WCE
	char *strdup(const char *src);
#endif
int iStrCmp(ILconst_string src1, ILconst_string src2);

//
// Some math functions
//
// A fast integer squareroot, completely accurate for x < 289.
// Taken from http://atoms.org.uk/sqrt/
// There is also a version that is accurate for all integers
// < 2^31, if we should need it
int iSqrt(int x);
//
// Useful miscellaneous functions
//
ILboolean	iCheckExtension(ILconst_string Arg, ILconst_string Ext);
ILboolean	iStrnCmpi(ILconst_string str1, ILconst_string str2, ILuint num);
ILbyte*		iFgets(char *buffer, ILuint maxlen);
ILboolean	iFileExists(ILconst_string FileName);
ILstring	iGetExtension(ILconst_string FileName);
ILstring	ilStrDup(ILconst_string Str);
ILsizei		ilStrLen(ILconst_string Str);
ILuint		ilCharStrLen(const char *Str);
//ILuint		ilLogfileClear();
ILuint		ilLogfileAppendto(ILconst_string message);
// Miscellaneous functions
void					ilDefaultStates(void);
ILenum					iGetHint(ILenum Target);
ILint					iGetInt(ILenum Mode);
void					ilRemoveRegistered(void);
ILAPI void ILAPIENTRY	ilSetCurImage(ILimage *Image);
ILuint					ilDetermineSize(ILenum Type);
//
// Rle compression
//
#define		IL_TGACOMP 0x01
#define		IL_PCXCOMP 0x02
#define		IL_SGICOMP 0x03
#define     IL_BMPCOMP 0x04
ILboolean	ilRleCompressLine(ILubyte *ScanLine, ILuint Width, ILubyte Bpp, ILubyte *Dest, ILuint *DestWidth, ILenum CompressMode);
ILuint		ilRleCompress(ILubyte *Data, ILuint Width, ILuint Height, ILuint Depth, ILubyte Bpp, ILubyte *Dest, ILenum CompressMode, ILuint *ScanTable);
void		iSetImage0(void);
// DXTC compression
ILuint			ilNVidiaCompressDXTFile(ILubyte *Data, ILuint Width, ILuint Height, ILuint Depth, ILenum DxtType);
ILAPI ILubyte*	ILAPIENTRY ilNVidiaCompressDXT(ILubyte *Data, ILuint Width, ILuint Height, ILuint Depth, ILenum DxtFormat, ILuint *DxtSize);
ILAPI ILubyte*	ILAPIENTRY ilSquishCompressDXT(ILubyte *Data, ILuint Width, ILuint Height, ILuint Depth, ILenum DxtFormat, ILuint *DxtSize);

// Conversion functions
ILboolean	ilAddAlpha(void);
ILboolean	ilAddAlphaKey(ILimage *Image);
ILboolean	iFastConvert(ILenum DestFormat);
ILboolean	ilFixCur(void);
ILboolean	ilFixImage(void);
ILboolean	ilRemoveAlpha(void);
ILboolean	ilSwapColours(void);
// Palette functions
ILboolean	iCopyPalette(ILpal *Dest, ILpal *Src);
// Miscellaneous functions
char*		iGetString(ILenum StringName);  // Internal version of ilGetString

//
// Image loading/saving functions
//
ILboolean ilLoadLInternal_JP2(const void *Lump, ILuint Size, ILimage *Image);
/* These get generated by ./configure script and included by ptr_defines.h header */
/*
ILboolean ilSaveImage(ILconst_string filename);
ILboolean ilIsValid_BLP(ILconst_string FileName);
...
...
ILboolean ilLoad_XPM(ILconst_string FileName);
ILboolean ilLoadF_XPM(ILHANDLE File);
ILboolean ilLoadL_XPM(const void *Lump, ILuint Size);
*/
// OpenEXR is written in C++, so we have to wrap this to avoid linker errors.
/*#ifndef IL_NO_EXR
	#ifdef __cplusplus
	extern "C" {
	#endif
		ILboolean ilLoad_EXR(ILconst_string FileName);
	#ifdef __cplusplus
	}
	#endif
#endif*/

//ILboolean ilLoad_EXR(ILconst_string FileName);


#ifdef __cplusplus
}
#endif

#endif//INTERNAL_H
